notifications:
  email: false
env:
  global:
  - REPO_DIR=pyo
  - BUILD_COMMIT=master
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  - sudo: required	
    services:	
    - docker	
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686 PRE_CMD=linux32
install:
- docker pull $DOCKER_IMAGE
script:
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels2010.sh
- pwd
- ls pyo/wheelhouse/
deploy:
  provider: releases
  skip_cleanup: true
  api_ley: $GITHUB_TOKEN
  draft: true
  file_glob: true
  file: pyo/wheelhouse/*whl
  overwrite: true
  on:
    repo: belangeo/pyo-linux-wheels
    all_branches: true
branches:
  except:
  - "/^untagged/"
