notifications:
  email: false
env:
  global:
  - REPO_DIR=pyo
  - BUILD_COMMIT=master
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686 PRE_CMD=linux32
install:
- docker pull $DOCKER_IMAGE
script:
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels2010.sh
- pwd
- ls pyo/wheelhouse/
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: yVRytoI4tK7FOQDkDSKYdauTpfYOSuOBVR3E7w4LhrGbuk1UrRjyF99w5zqmBEuhl+m+e3Xq6ixMHm2X0L1WSD+uUgG6zGIVfiT5Rc52qVxy+jQojB7bzdqcRxJg2TadzZGCOIZJW/cgazp9MA4YGnvmtmTiswJjMyRkkXiKAhVQiZmhZ6smLX1BsjM55Gvh8jO58GTrJJ6asddd9GTuqqOBgZK03hsTzOprtWfHxvrsTOPUL3HXgEr9iJj6FQl1K6ddZkuVeHs5HfA+f0gwOiziNi2PQVnM2GboFu+T8HhKU29pVwX+5eA8tdgXB1PO3K8IMn+h1mv7UG2zJrs62Jo721rbt57qU0HAOaPZiuRS/3Y5XWJwgpsosiL8FO0AIlykVAIhz+pBLZoQI7Vh6KKeXAlid8144NG8aCTMzu3kksfqtS8ncniX6+qW3bAwPBynSKLumTyDITKg1bi0NPv0cp/Nxp4OCs4Cg6TT7+9wX/oiPCz6TzwhgewJ0Ae0u5w4lquvaegp1AANbvuiCbASHG4CrCoM29SjvBc96FZ+++IAUD/WZHGNin3ahc1tzPVl3hOuXR31UWG12cYoHmhw+/OKgAR2nUHvBdO1+lNw3kdmQVwqc09KAKc/JWEt1waWhV2Fhoy2z21wtsx84wurFYfZvJwJrME5QYTt0cM=
  file_glob: true   
  file: pyo/wheelhouse/*whl
  overwrite: true
  on:
    repo: belangeo/pyo-linux-wheels
    all_branches: true

