notifications:
  email: false

env:
  global:
      - REPO_DIR=pyo
      - BUILD_COMMIT=master
matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - pwd
  - ls pyo/wheelhouse/
  
deploy:
  provider: releases
  api_key:
    secure: "WFdJo7VoY1XupQI7mzr+CiZEBnQABPEBfUdiHoLLeWEm9rduLOsp4e7LemD0W/VN9lKO48pTaXK1SHWvGfSKVtH6ZRrDdYPN0zfXVF3vplTpq6a5t5Gr4fvcG82DnhdT/vlAWDNnkefLA4KHvsmVxLSn4SxWA5PVaypQafHtua3/MyhQgC5kQIeCjIb5G/+H3PtbCXp1YiFjDVQ86HJtGi9F6sw/CRo4kFVi72bCSjMMtcN2SNi7LxxiPZBgUSAL3nEXcRs5x6jJ4EnbO0ap5UJb3yMx9wT5JBNm4J/kQ+9xqjbfMWvQWx59wDUlkdgVoPsoz+v0RBIhNBY6WoGwz2+5oetvz7IBuykyWCqw9gscZbDAXDQAZi9JNwvR9j3TsfDDPL8vknCYOdee9m6aIy5brvntmqdiMvv+bCh7TJspNl+ivbSozCKhPE9ettVugaW1DWBHMsMp9uxn/jp2ZQfOihxzQe0MzGRzBEylZsWTUfeNXso0N81Rz5Z1gHjIovD+x5WP8N6X3FW2oRcIMHGAvziGYJX8qnPZQg2HWruvwkcsF7BdMN4u0qYm7U+kdR9X7tdxt8y4aSxC9GA8y0iYqk5RsQs9mMgCjooknP2RtiQUUQmoRx9BDPvNwkEPP4my/y+tYQQAfxUGFZB/9+WSHzvI9wUSWKjF8bkTMik="
  file: "pyo/wheelhouse/*whl"
  skip_cleanup: true
  on:
    tags