notifications:
  email: false
env:
  global:
  - REPO_DIR=pyo
  - BUILD_COMMIT=master
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686 PRE_CMD=linux32
install:
- docker pull $DOCKER_IMAGE
script:
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels2014.sh
- pwd
- ls pyo/wheelhouse/
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 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
  draft: true
  file_glob: true
  file: pyo/wheelhouse/*whl
  overwrite: true
  on:
    repo: belangeo/pyo-linux-wheels
    all_branches: true
branches:
  except:
  - "/^untagged/"
before_install:
- openssl aes-256-cbc -K $encrypted_066e61ada3b7_key -iv $encrypted_066e61ada3b7_iv
  -in id_rsa_pyo_linux_wheels.enc -out id_rsa_pyo_linux_wheels -d
