notifications:
  email: false
env:
  global:
  - REPO_DIR=pyo
  - BUILD_COMMIT=master
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686 PRE_CMD=linux32
install:
- docker pull $DOCKER_IMAGE
script:
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels2014.sh
- pwd
- ls pyo/wheelhouse/
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "Bg0taUuG7RfeioQTHKs+HqVzB4yimd1iW6sCRyamF1QItQlR/f16GB5qoCGti8GBY3+xflBSbrYISbZridIfCETn1QGR90DrhM4Ly6zKykQfl38NiNRcABKJz/I/sd8OEVuI7ubo2u8STwzNQXwtB0dZwFlNuNXUSAVOBddcCDuiGnsBMje1YaGj+40vFj0jVaGCDh89xeA2g4adYICdMUJaZ4XvLvtnvlSNGEsFCdFHn5jxlr1duRo9jPwWd6mttqt7pR5kjsS8eP0Li0HB2hvdul6VIRJhtlDuoOMKxIVGKUhST5OyNWJARuc1SFIityrtFZIizsiTb+mhm2nf13PtE3XXLfWw7Jg77dS5HFuPtcGCQ/2D3sAnr2h0WQuL4NRdWAOl/3h2Z5v1oM6TjL+iA8rL8yRT/bR+oFwuwXRwjrDrPqmOdlok8ddaN3Bd2kVCna1DpYtfUijwmimAmDONbj8u8CtaK1FfJaC/Ro2+w4PlH4k5KchuS/1IyczYrIlzF8XK3dGT9pvvbY1CdCB342bNVqMx5qLW53KSOedkyrFwWkozhIpQDgK/TJmdRgvQiLoetK6gDGMe+e53xs0+Ycrq/6iYhs0plsYLBe7sqArUZz3qOxaB2nf7Zd1UHDLXoCoeltd6Wx38M61mDJ6VadlIh9WM/hFGu4FZ+6E="
  draft: true
  file_glob: true
  file: pyo/wheelhouse/*whl
  overwrite: true
  on:
    repo: belangeo/pyo-linux-wheels
    all_branches: true
branches:
  except:
  - "/^untagged/"
